Initial Itto Implementation
genshinsim/gcsim pull request #200
Opened 2022-01-25 22:25 UTC by Aftermathrar

Lots of brute forcing to get the frames values needed.

2022-01-30 03:14 UTC, srliao commented
is there any way to pull out the zhongli and geo traveler bug fixes from this and merge those first?

2022-02-08 19:10 UTC, HanSeoulOh commented
Itto review checklist
- [ ] A2 (fine because no understanding of atkspd currently)
- [x ] A4
- [ ] C1
- [ ] C2
- [ ] C4
- [ ] C6

2022-02-08 19:24 UTC, HanSeoulOh requested changes

2022-02-08 19:24 UTC, HanSeoulOh commented on internal/characters/itto/abil.go
> +
I believe you're missing setting the CD in Itto's skill

2022-02-12 05:38 UTC, HanSeoulOh approved these changes

2022-02-12 05:44 UTC, HanSeoulOh approved these changes
lgtm

2022-02-22 03:20 UTC, HanSeoulOh commented
worked https://gcsim.app/viewer/share/fSBTHCYz-_3gNZopzCE59

2022-02-22 03:21 UTC, merged