Jl 220216 add slingshot
genshinsim/gcsim pull request #290
Opened 2022-02-20 00:58 UTC by jordanlovato

My first draft of slingshot, not including any updates to approximate projectiles in the sim.

Please double check my updates, especially anything tagged with a TODO comment

2022-02-20 05:02 UTC, Tsym-or-Tysm requested changes

2022-02-20 21:06 UTC, jordanlovato commented on internal/weapons/bow/slingshot/slingshot.go
> +	}, fmt.Sprintf("slingshot-%v", char.Name()))
Agreed and done!

2022-02-20 21:08 UTC, jordanlovato commented
Note, I added an additional change here: https://github.com/genshinsim/gcsim/pull/290/commits/b2843b37be8892d4a2f1f60f93f2b1939be75446#diff-97fee3f9235ee50fa2dc1627cda0b12b053a8bb06277dfedbd770f72ed73afc0R60

I noticed dmg decrease from slingshot were not logging the negative value of the decrease

2022-02-21 22:18 UTC, Tsym-or-Tysm approved these changes
Looks good to me - as long as you tested the change and it looks good to you this is ready to merge from my perspective. Going to give this a day before I merge in case anyone else wants to look at it.

2022-02-22 03:58 UTC, merged