ayato frames update
genshinsim/gcsim pull request #458
Opened 2022-04-11 21:17 UTC by kurt22i

- Updates Ayato frames
- Fixes bugs with Ayato's CA and C4
- Sheet: https://docs.google.com/spreadsheets/d/1VL6nQvehIj8wTFC6ACC88p3i8lGUZnZV8Lx0G1dZp88/edit?usp=sharing
- Tested here: https://gcsim.app/viewer/share/perm_s25tFgmxjQxKqberSgeAY

2022-04-11 23:17 UTC, k0l11 commented
In case someone ever wants to use Physical Normal Attacks -> CA on Ayato in sims, I wanna mention that the following cancels are missing:
```
N2 -> CA
N3 -> CA
N4 -> CA
```

2022-04-12 00:02 UTC, srliao requested changes

2022-04-12 00:39 UTC, kurt22i commented on internal/characters/ayato/abil.go
> +		val[core.DmgP] = 0.2
fixed by @HanSeoulOh [here](https://github.com/genshinsim/gcsim/pull/459#issue-1200718859)

2022-04-12 00:45 UTC, HanSeoulOh commented on internal/characters/ayato/abil.go
> +		val[core.DmgP] = 0.2
resolved

2022-04-12 03:18 UTC, srliao approved these changes

2022-04-12 03:18 UTC, merged