fix fischl oz conditional breaking
genshinsim/gcsim pull request #776
Opened 2022-08-17 14:48 UTC by k0l11

fixes #608 

live:
https://next.gcsim.app/v3/viewer/share/93a380be-cb87-4219-b3e0-68d30e9e31e1
after fix:
https://next.gcsim.app/v3/viewer/share/0fd133a7-9af9-4a10-a4d6-771f76f79315

config:
```
options swap_delay=12 debug=true iteration=100 duration=100 workers=30;

fischl char lvl=90/90 cons=0 talent=9,9,9;
fischl add weapon="seasonedhuntersbow" refine=5 lvl=90/90;

# ----
target lvl=100 resist=0.1;

# ----
active fischl;
while 1 {
	fischl skill;
	if .status.fischloz == 0 {
		print("shouldn't happen");
	}
}
```

2022-08-20 23:49 UTC, shizukayuki requested changes
Since you removed the status from `queueOz` you need to add it back here too.
https://github.com/genshinsim/gcsim/blob/97f667514fbc1b5d46562fce5da8727f8fb685f1/internal/characters/fischl/burst.go#L26-L28

2022-08-20 23:49 UTC, shizukayuki commented on internal/characters/fischl/skill.go
> +		c.Core.Status.Add("fischloz", dur)
Can set it to `skillOzSpawn+dur` instead of using a task.

2022-08-21 14:53 UTC, k0l11 commented
I've removed the oz status for a bool that gets used for her custom oz conditional

2022-08-21 22:32 UTC, shizukayuki approved these changes

2022-08-22 12:53 UTC, srliao approved these changes

2022-08-22 12:53 UTC, merged