Add bloom, hyperbloom and burgeon reaction
genshinsim/gcsim pull request #952
Opened 2022-09-27 15:32 UTC by t3201v

Bloom, Hyperbloom and Burgeon reaction
Add couple characters' ability to target gadget on aoe attack (electro units/hyperbloom mostly): swirl, beidou, fischl, cooki, raiden, sucrose, yae

- [ ] Add `combat.TargetableGadget` on every other pyro/electro/anemo character (or maybe all characters)

2022-09-28 06:01 UTC, skippi requested changes
I think the bloom implementation fundamentally LGTM, but there's some issues in the core sim that are addressed in #953. Here's some preliminary comments until we can get that merged:

2022-09-28 08:42 UTC, t3201v commented on pkg/reactable/bloom.go
> +		s.Core.QueueAttack(ai, combat.NewCircleHit(s.Gadget, 5, false, combat.TargettableEnemy), -1, 1)
I have no idea either. I took it from the dendro imp notes https://github.com/genshinsim/gcsim/discussions/855#discussion-4330866 

> When the dendro core comes in contact with pyro, burgeon is triggered, dealing an attack with radius 5

2022-09-29 04:29 UTC, skippi requested changes
Almost there, I think we should go ahead and add `TargetableGadget` to the anemo/pyro units for a complete solution. If not pyro, at least the anemo infusions.

2022-09-29 21:37 UTC, srliao approved these changes

2022-09-29 21:37 UTC, merged